version: "3"
name: "base"

services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy:latest
        container_name: caddy
        ports:
            - 80:80
            - 443:443
        environment:
            CADDY_INGRESS_NETWORKS: caddy
        networks:
            - caddy
        restart: unless-stopped
        volumes:
            - caddy_data:/data
            - /var/run/docker.sock:/var/run/docker.sock:ro
        #labels:
        #    caddy.email: admin@mail.tld

    watchtower:
        image: containrrr/watchtower:latest
        environment:
            WATCHTOWER_CLEANUP: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    caddy_data:
        name: caddy_data

networks:
    caddy:
        name: caddy