#!/bin/sh
# grab urls from piped input or stdin
#  
# note: reportedly doesn't work with all versions of grep
#

prot='[a-zA-Z]+://'
host='[-a-zA-Z0-9._+]+'
path='[-a-zA-Z0-9._+#=?&:;%/!~()]+'

grep -Eo "$prot$host$path"
